name = "Kitai"
license = "GPL-3.0"
licenselink = "https://www.gnu.org/licenses/gpl-3.0.en.html#license-text"
description = "A simple yet pretty theme for hugo"

homepage = "https://github.com/me-sam9/kitai"

demosite = "https://sam9.xyz"

tags = ["blog", "simple", "minimal", "light"]
features = ["favicon", "images", "no javascript"]

[author]
    name = "Sam9"
    homepage = "https://sam9.xyz"
